### PR TITLE
리액트 초기화

### PR DESCRIPTION
**Pull request by Jindo-Dog**

### CODE REVIEW

**Comment by kimykstar** [comment]
good

**Comment by kimykstar** [comment]
good

**Comment by zxim** [comment]
good~

**Comment by kimykstar** [comment]
굿뜨

**Review by brianhhy — COMMENTED** [review]
very good

**Review by brianhhy — COMMENTED** [review]
veryverygood

**Review by kimykstar — APPROVED** [review]
good

**Review by zxim — APPROVED** [review]
very good

**Review by brianhhy — APPROVED** [review]
asd

**Pull request merged**
